### ISSUE TITLE
Volterra IDE produces errors

### ISSUE THREAD

**Issue by N-Lambrou** [lululxvi/deepxde#1368]
Hi @lululxvi, I tried to run the Volterra IDE demo but it produces the following error. I can’t figure out how to change the code to avoid the error.
`InvalidArgumentError                      Traceback (most recent call last)
File [~/ENTER/envs/tf/lib/python3.9/site-packages/tensorflow/python/client/session.py:1378], in BaseSession._do_call(self, fn, *args)
   1377 try:
-> 1378   return fn(*args)
   1379 except errors.OpError as e:

File [~/ENTER/envs/tf/lib/python3.9/site-packages/tensorflow/python/client/session.py:1361], in BaseSession._do_run.._run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1360 self._extend_graph()
-> 1361 return self._call_tf_sessionrun(options, feed_dict, fetch_list,
   1362                                 target_list, run_metadata)

File [~/ENTER/envs/tf/lib/python3.9/site-packages/tensorflow/python/client/session.py:1454], in BaseSession._call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1452 def _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list,
   1453                         run_metadata):
-> 1454   return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
   1455                                           fetch_list, target_list,
   1456                                           run_metadata)

InvalidArgumentError: Matrix size-incompatible: In[0]: [12,252], In[1]: [253,1]
	 [[{{node MatMul_3}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
...
  File "/Users/nicol/ENTER/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 795, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/Users/nicol/ENTER/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3814, in _create_op_internal
    ret = Operation(`

**Comment by lululxvi** [comment]
Could you try another backend?

**Comment by N-Lambrou** [comment]
I change the backend using the command `from deepxde.backend import paddle` and it gave the error `AttributeError: 'function' object has no attribute 'to_tensor'`. I think I didn’t change the backend correctly. How can I change the backend?

`AttributeError                            Traceback (most recent call last)
Cell In[11], line 55
     52 net = dde.nn.FNN(layer_size, activation, initializer)
     54 model = dde.Model(data, net)
---> 55 model.compile("L-BFGS")
     56 model.train()
     58 X = geom.uniform_points(100)

File [~/ENTER/envs/tf/lib/python3.9/site-packages/deepxde/utils/internal.py:22], in timing..wrapper(*args, **kwargs)
     19 @wraps(f)
     20 def wrapper(*args, **kwargs):
     21     ts = timeit.default_timer()
---> 22     result = f(*args, **kwargs)
     23     te = timeit.default_timer()
     24     if config.rank == 0:

File [~/ENTER/envs/tf/lib/python3.9/site-packages/deepxde/model.py:132], in Model.compile(self, optimizer, lr, loss, metrics, decay, loss_weights, external_trainable_variables)
    129     self.external_trainable_variables = external_trainable_variables
    131 if backend_name == "tensorflow.compat.v1":
--> 132     self._compile_tensorflow_compat_v1(lr, loss_fn, decay, loss_weights)
    133 elif backend_name == "tensorflow":
    134     self._compile_tensorflow(lr, loss_fn, decay, loss_weights)

File [~/ENTER/envs/tf/lib/python3.9/site-packages/deepxde/model.py:181], in Model._compile_tensorflow_compat_v1(self, lr, loss_fn, decay, loss_weights)
...
---> 20     int_mat = paddle.to_tensor(int_mat, dde.config.real(paddle), stop_gradient=False)
     21     rhs = paddle.mm(int_mat, y)
     22     lhs1 = paddle.grad(y, x, create_graph=True)[0]

AttributeError: 'function' object has no attribute 'to_tensor'`

**Comment by lululxvi** [comment]
https://deepxde.readthedocs.io/en/latest/user/installation.html#working-with-different-backends
