### ISSUE TITLE
Error on demo: Poisson_Dirichlet_1d

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [lululxvi/deepxde#138]
Hi Lu, thanks for sharing this work!

I tried to download deepxde and run Poisson_Dirichlet_1d demo, and the following error occured during the training:

```
Traceback (most recent call last):
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\utils.py", line 148, in _save_animation
    ani.save(filename, writer="imagemagick", fps=30)
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\animation.py", line 1109, in save
    writer = alt_writer(
TypeError: 'str' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\test.py", line 60, in <module>
    main()
  File ".\test.py", line 42, in main
    losshistory, train_state = model.train(
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\utils.py", line 52, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\model.py", line 154, in train
    self.callbacks.on_train_end()
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\callbacks.py", line 95, in on_train_end
    callback.on_train_end()
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\callbacks.py", line 364, in on_train_end
    save_animation(
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\utils.py", line 113, in save_animation
    apply(
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\utils.py", line 76, in apply
    r = p.apply(func, args=args, kwds=kwds)
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 357, in apply
    return self.apply_async(func, args, kwds).get()
  File "C:\Users\PC-REM\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
TypeError: 'str' object is not callable
```

Is this a known bug ?

Thanks for your help!

Rem

**Comment by lululxvi** [comment]
The error is from matplotlib, not DeepXDE. Did you install imagemagick, which is required to save the movie? You may try other examples.
