### ISSUE TITLE
Error in free-surface code

### ISSUE THREAD

**Issue by Nimava** [lululxvi/deepxde#1519]
Dear Professor, Based on the help of [forxltk](https://github.com/forxltk) on [#651](https://github.com/lululxvi/deepxde/issues/651), I try to wrote a code or solving linear surface wave. Here is that:

```
"""Backend supported: tensorflow.compat.v1, tensorflow, pytorch"""
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import deepxde as dde

def pde(x, u):  # x: x, y, t; u:, phi, eta
    # laplace equation: d^2_phi/d_x^2 + d^2_phi/d_y^2 = 0
    # dynamic free surface bc: d_phi/d_t + g*eta = 0
    # static free surface bc: d_eta/d_t - d_phi/d_y = 0
    phi = u[:, 0:1]
    eta = u[:, 1:2]
    g = -9.81
    tol = 1e-5
    dp_xx = dde.grad.hessian(u, x, component=0, i=0, j=0)
    dp_yy = dde.grad.hessian(u, x, component=0, i=0, j=1)
    laplace_eq = dp_xx + dp_yy

    fs_condition = tf.less(tf.abs(x[:, 1:2] - eta), tol)
    lmbd = tf.where(fs_condition, tf.ones_like(eta), tf.zeros_like(eta))
    dp_t = dde.grad.jacobian(u, x, i=0, j=2)
    de_t = dde.grad.jacobian(u, x, i=1, j=2)
    dp_y = dde.grad.jacobian(u, x, i=0, j=1)
    fs_eq1 = tf.cast(lmbd, dtype=tf.float32) * (dp_t + g * eta)
    fs_eq2 = tf.cast(lmbd, dtype=tf.float32) * (de_t - dp_y)

    return [laplace_eq, fs_eq1, fs_eq2]


def r_boundary(x,on_boundary):
    x,y,t = x
    return on_boundary and np.isclose(x,1)

def l_boundary(x,on_boundary):
    x,y,t = x
    return on_boundary and np.isclose(x,0)

def down_boundary(x,on_boundary):
    x,y,t = x
    return on_boundary and np.isclose(y,-1)

def func_zero(x):
    return np.zeros((len(x),1))

geom = dde.geometry.Rectangle([0, -1], [1, 0])
timedomain = dde.geometry.timedomain.TimeDomain(0, 1)
geomtime = dde.geometry.timedomain.GeometryXTime(geom, timedomain)
# Neumann BC for all walls
bc_l = dde.NeumannBC(geomtime, func_zero, l_boundary)
bc_r = dde.NeumannBC(geomtime, func_zero, r_boundary)
bc_low = dde.NeumannBC(geomtime, func_zero, down_boundary)

def boundary(_, on_initial):
    return on_initial

#Initial boundary conditions for phi and eta
ic1 = dde.icbc.IC(geomtime, lambda u: 0, boundary, component=0)
ic2 = dde.icbc.IC(geomtime, lambda x: 0.001 * tf.cos(np.pi * x[:, 0:1] / 2.0), boundary, component=1)

num_domain = 1000
num_boundary = 200
num_initial = 400
epochs = 1000
data = dde.data.TimePDE(
    geomtime,
    pde,
    [bc_l, bc_r, bc_low, ic1, ic2],
    num_domain=num_domain,
    num_boundary=num_boundary,
    num_initial=num_initial,
)

lr = 1e-3

net = dde.nn.FNN(
    [3] + [20] * 3 + [2], "tanh", "Glorot uniform"
)

# Define iterations and batch size
iterations = 100  # Define the number of training iterations
batch_size_ = 64  # Define the batch size for training
checker = dde.callbacks.ModelCheckpoint("model/model1.ckpt", save_better_only=True, period=1000)

# Create the DDE model
model = dde.Model(data, net)
#if dde.backend.backend_name == "tensorflow.compat.v1":
#    sess = tf.compat.v1.Session()    
#loss_weights = [10, 1, 1, 1, 1, 10]
model.compile(
        "adam",
        lr=lr,
        metrics=["l2 relative error"],
#        loss_weights=loss_weights,
)

losshistory, trainstate = model.train(epochs=epochs,batch_size = batch_size_,callbacks = [checker])
model.compile("L-BFGS-B")
dde.optimizers.set_LBFGS_options(
    maxcor=50,
)

dde.saveplot(losshistory, trainstate, issave=True, isplot=True)
dde.saveplot(losshistory, trainstate, issave=True, isplot=True)
dde.saveplot(losshistory, trainstate, issave=True, isplot=True)
```
I run it in the PC (also Google Colab). Here is the error:

```
Training model...

Traceback (most recent call last):
  File "F:\pinn\free_surface\f_s_v_04.py", line 96, in <module>
    losshistory, trainstate = model.train(epochs=epochs,batch_size = batch_size_,callbacks = [checker])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nvazi\miniconda3\envs\tf\Lib\site-packages\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nvazi\miniconda3\envs\tf\Lib\site-packages\deepxde\model.py", line 622, in train
    self._test()
  File "C:\Users\nvazi\miniconda3\envs\tf\Lib\site-packages\deepxde\model.py", line 831, in _test
    self.train_state.metrics_test = [
                                    ^
  File "C:\Users\nvazi\miniconda3\envs\tf\Lib\site-packages\deepxde\model.py", line 832, in <listcomp>
    m(self.train_state.y_test, self.train_state.y_pred_test)
  File "C:\Users\nvazi\miniconda3\envs\tf\Lib\site-packages\deepxde\metrics.py", line 12, in l2_relative_error
    return np.linalg.norm(y_true - y_pred) / np.linalg.norm(y_true)
                          ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```
I upgraded DeepXDE and used Tensorflow 2.x. Could you please help me? Many Thanks

**Comment by Nimava** [comment]
Dear [forxltk](https://github.com/forxltk), you are right. Many thanks. Your comments are always helpful and precise.
