### ISSUE TITLE
After I installed DeepxDE, guide the error JSON problem, and replace the deepxde version of the error error。json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 15 (char 14)

### ISSUE THREAD

**Issue by 1637936665** [lululxvi/deepxde#1674]
>>> import deepxde as dde
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\EL\lib\site-packages\deepxde\__init__.py", line 21, in <module>
    from . import backend
  File "D:\Anaconda\envs\EL\lib\site-packages\deepxde\backend\__init__.py", line 130, in <module>
    load_backend(get_preferred_backend())
  File "D:\Anaconda\envs\EL\lib\site-packages\deepxde\backend\__init__.py", line 107, in get_preferred_backend
    config_dict = json.load(config_file)
  File "D:\Anaconda\envs\EL\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Anaconda\envs\EL\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda\envs\EL\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda\envs\EL\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 15 (char 14)
>>> exit()

**Comment by 1637936665** [comment]
python=3.9.18，deepxde=1.11.0，I can use other computers. I tried to create other environments to install the module problem with the same environment. I don’t know where there is a problem.

**Comment by 1637936665** [comment]
> It is strange. What is your OS?

Windows 11
