### ISSUE TITLE
I want to use  dde.NeumannBC 

### ISSUE THREAD

**Issue by Poker-Pan** [lululxvi/deepxde#190]
I am running  Poisson_Neumann_1d.py  in examples.
but it can't work, can you help me?
![image](https://user-images.githubusercontent.com/49545046/103277120-3fc27d00-4a03-11eb-9998-557241cdf2eb.png)

**Comment by Poker-Pan** [comment]
Traceback (most recent call last):
  File "C:/Users/Poker丶Pan/PycharmProjects/Game/Deepxde/examples/Poisson_Neumann_1d.py", line 43, in <module>
    main()
  File "C:/Users/Poker丶Pan/PycharmProjects/Game/Deepxde/examples/Poisson_Neumann_1d.py", line 36, in main
    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
  File "C:\Users\Poker丶Pan\PycharmProjects\Game\Deepxde\deepxde\utils.py", line 52, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\Poker丶Pan\PycharmProjects\Game\Deepxde\deepxde\model.py", line 87, in compile
    self.losses = self.data.losses(self.net.targets, self.net.outputs, loss, self)
  File "C:\Users\Poker丶Pan\PycharmProjects\Game\Deepxde\deepxde\data\pde.py", line 96, in losses
    f = self.pde(model.net.inputs, outputs)
  File "C:/Users/Poker丶Pan/PycharmProjects/Game/Deepxde/examples/Poisson_Neumann_1d.py", line 13, in pde
    dy_xx = dde.grad.hessian(y, x)
  File "C:\Users\Poker丶Pan\PycharmProjects\Game\Deepxde\deepxde\gradients.py", line 162, in hessian
    return hessian._fn(ys, xs, component=component, i=i, j=j, grad_y=grad_y)
  File "C:\Users\Poker丶Pan\PycharmProjects\Game\Deepxde\deepxde\gradients.py", line 132, in __call__
    key = (y.ref(), xs.ref(), _component)
AttributeError: 'Tensor' object has no attribute 'ref'

Process finished with exit code 1

**Comment by lululxvi** [comment]
Use TensorFlow>=2.2.0

**Comment by Poker-Pan** [comment]
Thanks, i will go to try it.
