### ISSUE TITLE
Defining partial differential operators

### ISSUE THREAD

**Issue by aaronwtr** [lululxvi/deepxde#283]
Dear DeepXDE team, 

First of all thank you for making this software open and available for anyone to use. I am trying to use deepxde to solve a partial differential equation that is describing bacteriophage population dynamics, but probably because I am not that familiar with TensorFlow I am running in to the following problem: 

I have followed the ode_system example as provided in this repository and tried to rewrite it for my particular problem (see picture in attachments). I am not sure how to formulate this in the correct TF syntax. My attempt to this formulation is as follows: 
```python
def pde(x, t, y):
        b, l, p = y[:, 1:], y[:, 1:], y[:, 1:]
        T = b + l
        F = p / (T + Kb)

        db_tau = dde.grad.jacobian(y, t, i=0)
        dl_tau = dde.grad.jacobian(y, t, i=0)
        dp_tau = dde.grad.jacobian(y, t, i=0)
        db_xx = dde.grad.hessian(y, x, i=0)
        dl_xx = dde.grad.hessian(y, x, i=0)
        dp_xx = dde.grad.hessian(y, x, i=0)
        return ([db_tau - (db_xx + (G - F*b)),
                 dl_tau - (dl_xx - Omega*l + b*F),
                 dp_tau - (Dpr*dp_xx - T*h*F + l*Theta)]
                 )

```   

[pop_dyn_problem.pdf](https://github.com/lululxvi/deepxde/files/6446523/pop_dyn_problem.pdf)

**Comment by lululxvi** [comment]
The `pde` only takes two inputs, x and y, see https://deepxde.readthedocs.io/en/latest/demos/burgers.html

**Comment by aaronwtr** [comment]
@lululxvi Thank you! I think I now have written the pde correctly. I am still getting an error however. 
```python 
def main():
    def pde(x, y):
        b = 100     # initial number of bacteria
        p = 10      # initial number of phages
        l = 0       # initial number of infected bacteria

        T = b + l
        F = p / (T + Kb)

        db_tau = dde.grad.jacobian(y, x, i=0, j=1)
        dl_tau = dde.grad.jacobian(y, x, i=0, j=1)
        dp_tau = dde.grad.jacobian(y, x, i=0, j=1)
        db_xx = dde.grad.hessian(y, x, i=0, j=0)
        dl_xx = dde.grad.hessian(y, x, i=0, j=0)
        dp_xx = dde.grad.hessian(y, x, i=0, j=0)
        return ([db_tau - (db_xx + (G - F)*b),
                 dl_tau - (dl_xx - Omega*l + b*F),
                 dp_tau - (Dpr*dp_xx - T*h*F + l*Theta)]


        )

    def func(x):
        return 0

    geom = dde.geometry.Interval(-10, 10)
    timedomain = dde.geometry.TimeDomain(0, 30)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    bc = dde.DirichletBC(geomtime, func, lambda _, on_boundary: on_boundary)
    ic = dde.IC(geomtime, func, lambda _, on_initial: on_initial)
    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc, ic],
        num_domain=40,
        num_boundary=20,
        num_initial=10,
        solution=func,
        num_test=10000,
    )

    layer_size = [2] + [32] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    losshistory, train_state = model.train(epochs=10000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```
The constants are defined outside of the learning method. The error message I am receiving is: 
```
Traceback (most recent call last):
  File "C:/Users/Aaron/Desktop/Nanobiology/MSc/Advanced Modelling/Project/phage-population-dynamics/phage_pop_dyn_nn.py", line 134, in <module>
    main()
  File "C:/Users/Aaron/Desktop/Nanobiology/MSc/Advanced Modelling/Project/phage-population-dynamics/phage_pop_dyn_nn.py", line 60, in main
    losshistory, train_state = model.train(epochs=10000)
  File "C:\Users\Aaron\Desktop\Nanobiology\MSc\Advanced Modelling\Project\phage-population-dynamics\deepxde\deepxde\utils.py", line 52, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\Aaron\Desktop\Nanobiology\MSc\Advanced Modelling\Project\phage-population-dynamics\deepxde\deepxde\model.py", line 153, in train
    self._test(uncertainty)
  File "C:\Users\Aaron\Desktop\Nanobiology\MSc\Advanced Modelling\Project\phage-population-dynamics\deepxde\deepxde\model.py", line 279, in _test
    self.train_state.train_aux_vars,
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 958, in run
    run_metadata_ptr)
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1157, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape () for Tensor 'Placeholder_5:0', which has shape '(?, 1)'
```

**Comment by lululxvi** [comment]
```python
        return [db_tau - (db_xx + (G - F)*b),
                   dl_tau - (dl_xx - Omega*l + b*F),
                   dp_tau - (Dpr*dp_xx - T*h*F + l*Theta)]
```
