### ISSUE TITLE
unexpected keyword argument 'min_skip'

### ISSUE THREAD

**Issue by YitaoQiu** [lululxvi/deepxde#322]
Hi,

Has anyone seen this error before?

WARNING:tensorflow:From /home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "diffusion_1d.py", line 56, in <module>
    main()
  File "diffusion_1d.py", line 31, in main
    data = dde.data.TimePDE(
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/data/pde.py", line 262, in __init__
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/data/pde.py", line 96, in __init__
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/utils.py", line 24, in wrapper
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/data/pde.py", line 152, in train_next_batch
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/data/pde.py", line 277, in train_points
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/data/pde.py", line 203, in train_points
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/geometry/timedomain.py", line 79, in random_points
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/geometry/geometry_1d.py", line 52, in random_points
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/geometry/sampler.py", line 21, in sample
  File "/home/xxx/.conda/envs/tf2/lib/python3.8/site-packages/DeepXDE-0.11.2-py3.8.egg/deepxde/geometry/sampler.py", line 43, in quasirandom
**TypeError: __init__() got an unexpected keyword argument 'min_skip'**

**Comment by lululxvi** [comment]
It is due to scikit-optimize. It seems that you are using an unstable version of scikit-optimize. Install scikit-optimize 0.8.1 from pip or conda should solve this problem.
