### ISSUE TITLE
Errors while restoring model

### ISSUE THREAD

**Issue by usagigigi123** [lululxvi/deepxde#323]
Hi, Lu Lu! I was trying to solve the geometrically nonlinear beam problem while increasing the end load step by step. I wanted to load the saved model to predict the new one with a different load, but got the error message "Key beta1_power_2 not found in checkpoint[[{{node save_3/RestoreV2}}]]". Could you please help me to see what's the reason for this error? Thank you very much!

This is the code I've used:

P = 1
    
def ddy(x, y):
    return dde.grad.hessian(y, x)

def boundary_l(x, on_boundary):
    return on_boundary and np.isclose(x[0], 0)

def boundary_r(x, on_boundary):
    return on_boundary and np.isclose(x[0], 1)
    
def pde(x, y):
    return ddy(x,y) - P * tf.math.cos(y)

geom = dde.geometry.Interval(0, 1)

bc1 = dde.DirichletBC(geom, lambda x: 0, boundary_l)
bc2 = dde.NeumannBC(geom, lambda x: 0, boundary_r)

data = dde.data.PDE(
    geom,
    pde,
    [bc1, bc2],
    num_domain=20,
    num_boundary=2
)
layer_size = [1] + [20] * 3 + [1]
activation = "tanh"
initializer = "Glorot normal"
net = dde.maps.FNN(layer_size, activation, initializer)
    
    
model = dde.Model(data, net)
model.compile("adam", lr=0.001)
losshistory, train_state = model.train(epochs=10000, model_save_path = "./model/model.ckpt")

P=2
    
data = dde.data.PDE(
    geom,
    pde,
    [bc1, bc2],
    num_domain=20,
    num_boundary=2
)
      
model = dde.Model(data, net)
model.compile("adam", lr=0.001)
model.restore(r"./model/model.ckpt-10000", verbose = 1) 
losshistory, train_state = model.train(epochs=10000
                                     # , callbacks=[checker]
                                      # ,model_restore_path = "./model/model.ckpt-10000"
                                      )

This is the error message I got:

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1348       self._extend_graph()
-> 1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
   1350                                       target_list, run_metadata)

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1440                           run_metadata):
-> 1441     return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
   1442                                             fetch_list, target_list,

NotFoundError: Key beta1_power_2 not found in checkpoint
	 [[{{node save_5/RestoreV2}}]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py in restore(self, sess, save_path)
   1297       else:
-> 1298         sess.run(self.saver_def.restore_op_name,
   1299                  {self.saver_def.filename_tensor_name: save_path})

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    956     try:
--> 957       result = self._run(None, fetches, feed_dict, options_ptr,
    958                          run_metadata_ptr)

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1179     if final_fetches or final_targets or (handle and feed_dict_tensor):
-> 1180       results = self._do_run(handle, final_targets, final_fetches,
   1181                              feed_dict_tensor, options, run_metadata)

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
-> 1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
   1359                            run_metadata)

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 

NotFoundError: Key beta1_power_2 not found in checkpoint
	 [[node save_5/RestoreV2 (defined at F:\DeepXDE\deepxde\deepxde\model.py:204) ]]

Original stack trace for 'save_5/RestoreV2':
  File "F:\anaconda3\envs\tf\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\anaconda3\envs\tf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "F:\anaconda3\envs\tf\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
    self.io_loop.start()
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "F:\anaconda3\envs\tf\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "F:\anaconda3\envs\tf\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "F:\anaconda3\envs\tf\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
    self.do_execute(
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 2894, in run_cell
    result = self._run_cell(
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 2940, in _run_cell
    return runner(coro)
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 3165, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 3357, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-00a8cf55192e>", line 14, in <module>
    model.compile("adam", lr=0.001)
  File "F:\DeepXDE\deepxde\deepxde\utils.py", line 52, in wrapper
    result = f(*args, **kwargs)
  File "F:\DeepXDE\deepxde\deepxde\model.py", line 82, in compile
    self._open_tfsession()
  File "F:\DeepXDE\deepxde\deepxde\model.py", line 204, in _open_tfsession
    self.saver = tf.train.Saver(max_to_keep=None)
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 836, in __init__
    self.build()
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 876, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 515, in _build_internal
    restore_op = self._AddRestoreOps(filename_tensor, saveables,
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 335, in _AddRestoreOps
    all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1520, in restore_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in get_tensor(self, tensor_str)
     68   try:
---> 69     return CheckpointReader.CheckpointReader_GetTensor(
     70         self, compat.as_bytes(tensor_str))

RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py in restore(self, sess, save_path)
   1308       try:
-> 1309         names_to_keys = object_graph_key_mapping(save_path)
   1310       except errors.NotFoundError:

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py in object_graph_key_mapping(checkpoint_path)
   1626   reader = py_checkpoint_reader.NewCheckpointReader(checkpoint_path)
-> 1627   object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
   1628   object_graph_proto = (trackable_object_graph_pb2.TrackableObjectGraph())

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in get_tensor(self, tensor_str)
     73   except RuntimeError as e:
---> 74     error_translator(e)
     75 

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in error_translator(e)
     34       'matching files for') in error_message:
---> 35     raise errors_impl.NotFoundError(None, None, error_message)
     36   elif 'Sliced checkpoints are not supported' in error_message or (

NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-10-00a8cf55192e> in <module>
     13 model = dde.Model(data, net)
     14 model.compile("adam", lr=0.001)
---> 15 model.restore(r"./model/model.ckpt-10000", verbose = 1)
     16 losshistory, train_state = model.train(epochs=10000
     17                                      # , callbacks=[checker]

F:\DeepXDE\deepxde\deepxde\model.py in restore(self, save_path, verbose)
    375         if verbose > 0:
    376             print("Restoring model from {} ...\n".format(save_path))
--> 377         self.saver.restore(self.sess, save_path)
    378 
    379 

F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py in restore(self, sess, save_path)
   1312         # is a graph mismatch. Re-raise the original error with
   1313         # a helpful message (b/110263146)
-> 1314         raise _wrap_restore_error_with_msg(
   1315             err, "a Variable name or other graph key that is missing")
   1316 

NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key beta1_power_2 not found in checkpoint
	 [[node save_5/RestoreV2 (defined at F:\DeepXDE\deepxde\deepxde\model.py:204) ]]

Original stack trace for 'save_5/RestoreV2':
  File "F:\anaconda3\envs\tf\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\anaconda3\envs\tf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "F:\anaconda3\envs\tf\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
    self.io_loop.start()
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "F:\anaconda3\envs\tf\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "F:\anaconda3\envs\tf\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "F:\anaconda3\envs\tf\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
    self.do_execute(
  File "F:\anaconda3\envs\tf\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "F:\anaconda3\envs\tf\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 2894, in run_cell
    result = self._run_cell(
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 2940, in _run_cell
    return runner(coro)
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 3165, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 3357, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "F:\anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-00a8cf55192e>", line 14, in <module>
    model.compile("adam", lr=0.001)
  File "F:\DeepXDE\deepxde\deepxde\utils.py", line 52, in wrapper
    result = f(*args, **kwargs)
  File "F:\DeepXDE\deepxde\deepxde\model.py", line 82, in compile
    self._open_tfsession()
  File "F:\DeepXDE\deepxde\deepxde\model.py", line 204, in _open_tfsession
    self.saver = tf.train.Saver(max_to_keep=None)
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 836, in __init__
    self.build()
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 876, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 515, in _build_internal
    restore_op = self._AddRestoreOps(filename_tensor, saveables,
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 335, in _AddRestoreOps
    all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\training\saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1520, in restore_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "F:\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by lululxvi** [comment]
The issue could be due to that you use Windows... Do you have a Linux to try?

**Comment by Haroncf** [comment]
Hi lulu,
I have the same problem and **I can't test in Ubuntu/Linux.** 
However, what I realized about this problem:
 - If I compile/train the model, restart the kernel on my jupyter notebook, and restore the model. **It will work.**
 - If I compile/train the model, and try to restore the model without restart the kernel. **It will not work.**

I need to train the model with a lot diferente datasets. So I will use a loop to compile/train/save, change the dataset, restore the model, and train again. A example with a simple code:

```
> model = dde.Model(data, net)
> model.compile("adam", learning_rate, loss_weights)
> model.train(iterations=1500, model_save_path="./result/adam_bfgs-1000.ckpt")

> model = dde.Model(data2, net)
> model.compile("adam", learning_rate, loss_weights)
> model.restore(save_path="./result/adam_bfgs-1000.ckpt")

NotFoundError: 2 root error(s) found.
  (0) NOT_FOUND: Key beta1_power not found in checkpoint
	 [[{{node save_1/RestoreV2}}]]
	 [[save_1/RestoreV2/_43]]
  (1) NOT_FOUND: Key beta1_power not found in checkpoint
	 [[{{node save_1/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.
```
I didn't understand why it occurs if I don't restart the kernel on my jupyter notebook.
I also tried to change the variable name "model2 = dde.Model(data2, net)", and it did not work.

**Did you resolved this problem?**

Thanks a lot
Haron CF
