### ISSUE TITLE
Boundary and initial conditions for a coupled PDE

### ISSUE THREAD

**Issue by sashahexe** [lululxvi/deepxde#325]
``Dear Lulu, thank you for your great effort in making DeepXDE available for the community. I am sure it will allow a lot of fruitful research in the future. 

I am trying to set up a solution of a coupled PDE system for a diffusion process accompanied by an adsorption process which calculates two concentrations cp and cq .

My intention is to have IC as zero and BC as:

cq = cp = 0 (t=0)

cp = cp_sat (at t>=0)
cq = cq_sat (at t>=0)

The program seems to have a problem with the dimensions either in the bc or ic. Could you please help me out with this.
I have read the examples and tried to grasp the idea of how the dimensions of the x are related to the bc and ic setup but after a number of trials I am still getting an error:

`IndexError: list index out of range`

Here is the code:
` 
    
    
    def main():
        kf = tf.Variable(0.05)
        D = tf.Variable(1.0)
        cq_sat = tf.Variable(0.3)
        cp_sat = tf.Variable(0.003)
    
///////

        def fun_bc_cp(x):
            return cp_sat
        
        def fun_bc_cq(x):
            return cq_sat
    
        def fun_init(x):
            return np.exp(-20 * x[:, 0:1])
        
    
        geom = dde.geometry.Interval(0, 1)
        timedomain = dde.geometry.TimeDomain(0, 10)
        geomtime = dde.geometry.GeometryXTime(geom, timedomain)
    
        bc_p = dde.DirichletBC(geomtime, lambda x: cp_sat, lambda _, on_boundary: on_boundary, component=0)
        bc_q = dde.DirichletBC(geomtime, lambda x: cq_sat, lambda _, on_boundary: on_boundary, component=1)
        ic1 = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial, component=0)
        ic2 = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial, component=1)
  ``

Thank you and I am looking forward to your response!

Best regards,
Alexandra

**Comment by lululxvi** [comment]
```python
    kf = 0.05
    D = 1.0
    cq_sat = 0.3
    cp_sat = 0.003
```

**Comment by sashahexe** [comment]
Unfortunately changing that part did not help, I get the following errors:


  File "/home/sasha/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3600, in _as_graph_element_locked
    raise TypeError("Can not convert a %s into a %s." %

TypeError: Can not convert a float into a Tensor or Operation.

TypeError: Fetch argument 0.05 has invalid type <class 'float'>, must be a string or Tensor. (Can not convert a float into a Tensor or Operation.)

I changed your suggestion to 

`    kf = tf.constant(0.05)
    D = tf.constant(1.0)
    cq_sat = tf.constant(0.3)
    cp_sat = tf.constant(0.003)
`

That worked but i still get an error:

Warning: 50000 points required, but 50055 points sampled.
Compiling model...
Building feed-forward neural network...
'build' took 0.027099 s


  File "/home/sasha/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py", line 872, in __getitem__
    return self._dims[key]

IndexError: list index out of range

**Comment by sashahexe** [comment]
Here is the full output of what I get, it never comes to training just that, could you please help with the solution, we are really interested in using your library for our research. It would be really nice of you and thank you for your time!



runcell(0, '/home/sasha/Documents/Nextcloud/RESEARCH/DeepXDE/diffusion_adsorption_direct')
Using TensorFlow 2 backend.

WARNING:tensorflow:From /home/sasha/anaconda3/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Warning: 50000 points required, but 50055 points sampled.
Compiling model...
Building feed-forward neural network...
WARNING:tensorflow:From /home/sasha/anaconda3/lib/python3.8/site-packages/deepxde/maps/fnn.py:105: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /home/sasha/anaconda3/lib/python3.8/site-packages/tensorflow/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
'build' took 0.031306 s

Traceback (most recent call last):

  File "/home/sasha/Documents/Nextcloud/RESEARCH/DeepXDE/diffusion_adsorption_direct", line 68, in <module>
    main()

  File "/home/sasha/Documents/Nextcloud/RESEARCH/DeepXDE/diffusion_adsorption_direct", line 59, in main
    model.compile("adam", lr=0.001)

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/deepxde/utils.py", line 52, in wrapper
    result = f(*args, **kwargs)

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/deepxde/model.py", line 87, in compile
    self.losses = self.data.losses(self.net.targets, self.net.outputs, loss, self)

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/deepxde/data/pde.py", line 148, in losses
    return tf.cond(tf.equal(model.net.data_id, 0), losses_train, losses_test)

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1227, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1064, in BuildCondBranch
    original_result = fn()

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/deepxde/data/pde.py", line 133, in losses_train
    error = bc.error(self.train_x, model.net.inputs, outputs, beg, end)

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/deepxde/boundary_conditions.py", line 54, in error
    if not isinstance(values, numbers.Number) and values.shape[1] != 1:

  File "/home/sasha/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py", line 872, in __getitem__
    return self._dims[key]

IndexError: list index out of range


2021-07-10 17:25:39.685044: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-07-10 17:25:39.705482: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3799900000 Hz
2021-07-10 17:25:39.705954: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd92c000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-07-10 17:25:39.705996: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-07-10 17:25:39.707188: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-07-10 17:25:39.752358: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-10 17:25:39.752605: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564ee5d9ef10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-07-10 17:25:39.752619: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1050 Ti, Compute Capability 6.1
2021-07-10 17:25:39.752760: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-10 17:25:39.752914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 Ti computeCapability: 6.1
coreClock: 1.4175GHz coreCount: 6 deviceMemorySize: 3.94GiB deviceMemoryBandwidth: 104.43GiB/s
2021-07-10 17:25:39.753072: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-07-10 17:25:39.754025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-07-10 17:25:39.754966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-07-10 17:25:39.755126: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-07-10 17:25:39.756052: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-07-10 17:25:39.756649: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-07-10 17:25:39.759314: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-07-10 17:25:39.759411: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-10 17:25:39.759620: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-10 17:25:39.759757: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-07-10 17:25:39.759789: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-07-10 17:25:39.760022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-10 17:25:39.760032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2021-07-10 17:25:39.760036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2021-07-10 17:25:39.760102: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-10 17:25:39.760273: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-10 17:25:39.760560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3385 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
