### ISSUE TITLE
Error running Poisson_Dirichlet_1d.py

### ISSUE THREAD

**Issue by kaluzaklein** [lululxvi/deepxde#5]
I'm running in a conda env.

Here is the error:

Saving the movie of function to model/movie_x.txt, model/movie_y.txt, model/movie_y.gif...
Traceback (most recent call last):
  File "Poisson_Dirichlet_1d.py", line 59, in <module>
    main()
  File "Poisson_Dirichlet_1d.py", line 43, in main
    epochs=10000, callbacks=[checkpointer, movie]
  File "//anaconda2/lib/python2.7/site-packages/deepxde/utils.py", line 50, in wrapper
    result = f(*args, **kwargs)
  File "//anaconda2/lib/python2.7/site-packages/deepxde/model.py", line 119, in train
    self.callbacks.on_train_end()
  File "//anaconda2/lib/python2.7/site-packages/deepxde/callbacks.py", line 95, in on_train_end
    callback.on_train_end()
  File "//anaconda2/lib/python2.7/site-packages/deepxde/callbacks.py", line 359, in on_train_end
    fname_movie, np.ravel(self.x), self.y, y_reference=y_reference
  File "//anaconda2/lib/python2.7/site-packages/deepxde/utils.py", line 105, in save_animation
    kwds={"y_reference": y_reference, "logy": logy},
  File "//anaconda2/lib/python2.7/site-packages/deepxde/utils.py", line 66, in apply
    with Pool(1) as p:
AttributeError: __exit__

The error does not occur if I comment out the movie and remove movie from the callbacks.

**Comment by lululxvi** [comment]
The movie is saved using matplotlib.animation with imagemagick writer. The error is highly due to the failure of calling imagemagick. Which operator system are you using? Win or Linux?

**Comment by kaluzaklein** [comment]
Replacing "with Pool(1) as p:" with "p = Pool(5)" and de-indenting the block, crashes with this output:

Saving the movie of function to model/movie_x.txt, model/movie_y.txt, model/movie_y.gif...
Process PoolWorker-1:
Traceback (most recent call last):
  File "//anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "//anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "//anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "//anaconda2/lib/python2.7/multiprocessing/queues.py", line 376, in get
    return recv()
AttributeError: 'module' object has no attribute '_save_animation'


It can't be killed with keyboard interrupt, there are messages like this:
    racquire()
KeyboardInterrupt
    racquire()
    return recv()
KeyboardInterrupt
KeyboardInterrupt
    racquire()
    racquire()
KeyboardInterrupt
KeyboardInterrupt

**Comment by lululxvi** [comment]
Sorry for the confusion. I mean you just run the following 2 line codes in the Python environment to test `Pool`:

    from multiprocessing import Pool
    p = Pool(1)

**Comment by kaluzaklein** [comment]
Those lines run with no problems.

**Comment by lululxvi** [comment]
The problem is Python 2. `with` clause for multiprocessing is supported in Python 3. It would be great If you could switch to Python 3, otherwise, I can show you how to modify the function `apply` in `utils.py`.

**Comment by tangqi** [comment]
HI, I have another issue to run this example. Here is my error message
```
Traceback (most recent call last):
  File "Poisson_Dirichlet_1d.py", line 59, in <module>
    main()
  File "Poisson_Dirichlet_1d.py", line 43, in main
    epochs=10000, callbacks=[checkpointer, movie]
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/site-packages/deepxde/utils.py", line 50, in wrapper
    result = f(*args, **kwargs)
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/site-packages/deepxde/model.py", line 148, in train
    self.callbacks.on_train_end()
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/site-packages/deepxde/callbacks.py", line 95, in on_train_end
    callback.on_train_end()
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/site-packages/deepxde/callbacks.py", line 359, in on_train_end
    fname_movie, np.ravel(self.x), self.y, y_reference=y_reference
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/site-packages/deepxde/utils.py", line 105, in save_animation
    kwds={"y_reference": y_reference, "logy": logy},
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/site-packages/deepxde/utils.py", line 74, in apply
    r = p.apply(func, args=args, kwds=kwds)
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/multiprocessing/pool.py", line 259, in apply
    return self.apply_async(func, args, kwds).get()
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: 'MovieWriterRegistry' object is not an iterator
```
I am using python 3.6.10 and tensorflow 1.13.2. I installed through `conda install -c conda-forge deepxde` Did I miss something?

Another question, have you tried to install your package on hpc using GPUs? I tried on nersc but did not succeed. Any suggestions?

Thanks a lot for the help.
-qi

**Comment by lululxvi** [comment]
- The animation relies on [imagemagick](https://imagemagick.org/). Do you have it? If you don't need the movie, you can comment out the `movie` callback.
- TensorFlow does not have a good support of HPC. You need other tools, like [Horovod](https://github.com/horovod/horovod).

**Comment by tangqi** [comment]
Thanks for your quick response. imagemagick appears to be missing in my environment.

I get your code working using the cpu version of tensorflow on nersc. There are some incompatibility issue with their gpu version. But I think I can live with that for now. Thanks again.
