### ISSUE TITLE
Errors when setting float64 in Lorenz_inverse example

### ISSUE THREAD

**Issue by mlin26** [lululxvi/deepxde#551]
Dear Dr. Lu,

I am trying to set double float precision in one of the inverse example: https://github.com/lululxvi/deepxde/blob/master/examples/pinn_inverse/Lorenz_inverse.py. 

When I add "dde.config.real.set_float64()" at the begining of the code, it shows error:
```
Traceback (most recent call last):

  File "X:\PINNWD\deepxde-master\examples\Lorenz_inverse.py", line 65, in <module>
    model.compile("adam", lr=0.001, external_trainable_variables=[C1, C2, C3])

  File "C:\Users\mlin4\Anaconda3\envs\DeepXDE\lib\site-packages\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)

  File "C:\Users\mlin4\Anaconda3\envs\DeepXDE\lib\site-packages\deepxde\model.py", line 107, in compile
    self._compile_tensorflow_compat_v1(lr, loss_fn, decay, loss_weights)

  File "C:\Users\mlin4\Anaconda3\envs\DeepXDE\lib\site-packages\deepxde\model.py", line 127, in _compile_tensorflow_compat_v1
    losses = self.data.losses(self.net.targets, self.net.outputs, loss_fn, self)

  File "C:\Users\mlin4\Anaconda3\envs\DeepXDE\lib\site-packages\deepxde\data\pde.py", line 129, in losses
    f = self.pde(model.net.inputs, outputs)

  File "X:\PINNWD\deepxde-master\examples\Lorenz_inverse.py", line 31, in Lorenz_system
    dy1_x - C1 * (y2 - y1),

  File "C:\Users\mlin4\Anaconda3\envs\DeepXDE\lib\site-packages\tensorflow\python\ops\variables.py", line 1078, in _run_op
    return tensor_oper(a.value(), *args, **kwargs)

  File "C:\Users\mlin4\Anaconda3\envs\DeepXDE\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "C:\Users\mlin4\Anaconda3\envs\DeepXDE\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 550, in _apply_op_helper
    raise TypeError(

TypeError: Input 'y' of 'Mul' Op has type float64 that does not match type float32 of argument 'x'.
```

I am not using the most up-to-date deepxde. My deepxde version is '0.14.0'. Could you tell me how to solve this problem? Thanks!

**Comment by mlin26** [comment]
I also try the latest version 1.1.1, it has the same error.

**Comment by mlin26** [comment]
I got it. I need also set variable to float64.

```
# Change dde.Variable(1.0) to:
dde.Variable(1.0, dtype='float64') 
```

**Comment by mlin26** [comment]
Dr. Lu, I still have another question. How can we initialize a variable if it contains more than one value, for example, can we train NN use:
`dde.Variable([1.0, 1.0])`

I have tried this, but it shows an error:
`TypeError: unsupported format string passed to numpy.ndarray.__format__`

Thanks!

**Comment by lululxvi** [comment]
The simple solution is using two variables.

But the way you did should be correct. The code shouldn't throw an error of `numpy.ndarray.__format__`. Could you provide more information?
