### ISSUE TITLE
Create complex boundaries with OperatorBC

### ISSUE THREAD

**Issue by railleon** [lululxvi/deepxde#619]
Dear Dr Lu @lululxvi 

I would like to create a boundary with OperatorBC. The function of this boundary may be a bit more complicated than the previous cases you provided, I would like to know how to define such a boundary, the case of the boundary and my current code is as follows, thank you for your help!

![262d1235dc8cc9b349f8f3dbb5c3bfb](https://user-images.githubusercontent.com/103068333/163432848-c5ffb6b6-c842-4ff6-a078-12f61dbf6483.jpg)

def fun(x,y,X):

    u_x=dde.grad.jacobian(y, x,i=0,j=0)
    v_y = dde.grad.jacobian(y, x, i=1, j=1)

    return  u_x+v_y-X[:,2:3]

bc_1 = dde.icbc.OperatorBC(geomtime,  fun, boundary)

**Comment by lululxvi** [comment]
It looks good.

**Comment by railleon** [comment]
@lululxvi  Thanks for your reply and kind help!

But I'm getting an error when running that code, and I feel that the error seems to be caused by the fact that u_x+v_y and X[2:3] have different scales. The error is reported as follows, where [172,1] seems to be the scale of the former while [235,1] seems to be the scale of the latter.

tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [172,1] vs. [235,1]
	

Do you know how to solve this?

**Comment by lululxvi** [comment]
Are you sure that the error is here? How about deleting `X[2:3]` and then can the code run?

**Comment by railleon** [comment]
@lululxvi  yes, when I delete the X[2:3], the code run. Here I can give you another example, which failed with the same problem. Please help me to see what the problem is.

`geom = dde.geometry.Rectangle([-5, -5], [5, 5])
UP = np.array([-5,5]) + np.array([10, 0]) * lhs(2, 6000)

def pde(x, y):
    u_xx=dde.grad.hessian(y, x, component=0, i=0, j=0)
    u_yy = dde.grad.hessian(y, x, component=0, i=1, j=1)
    u_xy = dde.grad.hessian(y, x, component=0, i=0, j=1)
    v_xx = dde.grad.hessian(y, x, component=1, i=0, j=0)
    v_yy = dde.grad.hessian(y, x, component=1, i=1, j=1)
    v_xy = dde.grad.hessian(y, x, component=1, i=0, j=1)
    eq_1=u_xx+v_xy+u_yy+v_xy+y[:,0:1]
    eq_2 =u_xy+v_xx+u_xy+v_yy +y[:,1:2]
    return [eq_1, eq_2]

def boundary_up(x, on_boundary):
    return on_boundary and np.isclose(x[1], 5)

def fun_up(x,y,X):
    u_x = dde.grad.jacobian(y, x, i=0, j=0)
    v_y = dde.grad.jacobian(y, x, i=1, j=1)
    amplitude = 1 * np.exp(-((X[:,0:1] ) / 0.2) ** 2)
    xx=u_x+v_y-amplitude
    return xx

bc = dde.icbc.OperatorBC(geom,  fun_up, boundary_up)

data = dde.data.PDE(
    geom,
    pde,
    bc,
    num_domain=1000,
    num_boundary=0,
    num_test=200,
    anchors=UP)

layer_size = [2] + [80] * 6 + [2]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.maps.FNN(
    layer_size, activation, initializer
)

model = dde.Model(data, net)

dde.optimizers.set_LBFGS_options(gtol=1e-12, maxiter=10)

model.compile(    "L-BFGS-B")

pde_residual_resampler = dde.callbacks.PDEResidualResampler(period=100)
losshistory, train_state = model.train(  callbacks=[pde_residual_resampler], display_every=100, model_save_path="./model/trained-model")`

The error is shown as follows, I think the scale of X[:,0:1]  may be consistent with the number of all data, but the scale of u_x may only be consistent with the number of data on the boundary, thus causing a mismatch, but I don't know how to correct my code.  Thank you very much for your kind help!
`
'compile' took 1.245254 s

Initializing variables...
2022-04-25 21:34:08.532023: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
Training model...

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [6225,1] vs. [13000,1]
	 [[{{node add_8}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/example.py", line 85, in <module>
    losshistory, train_state = model.train(  callbacks=[pde_residual_resampler], display_every=100, model_save_path="./model/trained-model")
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\model.py", line 414, in train
    self._test()
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\model.py", line 552, in _test
    self.train_state.y_pred_test, self.train_state.loss_test = self._outputs_losses(
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\model.py", line 337, in _outputs_losses
    return self.sess.run(self.outputs_losses, feed_dict=feed_dict)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [6225,1] vs. [13000,1]
	 [[node add_8 (defined at D:/01.lrh in uk/0.2022/11.PINN/1.dex/example.py:54) ]]

Errors may have originated from an input operation.
Input Source operations connected to node add_8:
 strided_slice_16 (defined at C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\gradients.py:73)

Original stack trace for 'add_8':
  File "D:/01.lrh in uk/0.2022/11.PINN/1.dex/example.py", line 82, in <module>
    model.compile(    "L-BFGS-B")
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\model.py", line 108, in compile
    self._compile_tensorflow_compat_v1(lr, loss_fn, decay, loss_weights)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\model.py", line 130, in _compile_tensorflow_compat_v1
    losses = self.data.losses(self.net.targets, self.net.outputs, loss_fn, self)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\data\pde.py", line 154, in losses
    error = bc.error(self.train_x, model.net.inputs, outputs, beg, end)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\deepxde\icbc\boundary_conditions.py", line 154, in error
    return self.func(inputs, outputs, X)[beg:end]
  File "D:/example.py", line 54, in fun_up
    xx=u_x+v_y-amplitude
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1164, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1486, in _add_dispatch
    return gen_math_ops.add_v2(x, y, name=name)
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 480, in add_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\framework\ops.py", line 3528, in _create_op_internal
    ret = Operation(
  File "C:\ProgramData\Anaconda3\envs\dep\lib\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()

`

**Comment by railleon** [comment]
@lululxvi  Also, I would also like to ask if only Dirichlet boundaries can be set as hard boundaries? 
If boundaries like the one I implemented with OperatorBC above cannot be set as hard boundaries?

Thank you very much for your kind help!

**Comment by lululxvi** [comment]
- It is a bug of DeepXDE. Use `x` instead of `X`:
```python
amplitude = tf.exp(-(x[:,0:1] / 0.2) ** 2)
```
- For hard BC, see https://doi.org/10.1137/21M1397908 and the references there.
