### ISSUE TITLE
Early Stopping Over Stoke Eqn

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#63]
Dear @lululxvi 

I am trying to implement early stopping over Stoke Equation.

Unfortunately, I am getting an error:

```
Traceback (most recent call last):

  File "D:\PhD_Box\Code\Project_1\Stoke_DeepXDE\stoke.py", line 179, in <module>
    main()

  File "D:\PhD_Box\Code\Project_1\Stoke_DeepXDE\stoke.py", line 142, in main
    print("Adding new point:", X[x_id], "\n")

IndexError: index 1952 is out of bounds for axis 0 with size 1000
```

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np


import sys
sys.path.insert( 0, "D:/PhD_Box/Code/Project_1/Stoke_2_DeepXDE/deepxde-master/deepxde-master")

import deepxde as dde

import tensorflow as tf


def main():

    def pde( x, y ):

        u, v, p = y[:, 0:1], y[:, 1:2 ], y[:, 2:3]

        du_x = tf.gradients( u , x )[0]
        dv_x = tf.gradients( v , x )[0]
        dp_x = tf.gradients( p , x )[0]

        dp_x, dp_y = dp_x[:, 0:1 ], dp_x[:, 1:2 ]

        du_x, du_y = du_x[:, 0:1], du_x[:, 1:2 ]

        dv_x, dv_y = dv_x[:, 0:1], dv_x[ :, 1:2 ]

        du_xx = tf.gradients( du_x, x )[0][:, 0:1 ]
        du_yy = tf.gradients( du_y, x )[0][:, 1:2 ]

        dv_xx = tf.gradients( dv_x, x)[0][:, 0:1 ]
        dv_yy = tf.gradients( dv_y, x)[0][:, 1:2 ]


        return [-( du_xx + du_yy ) + dp_x,
                -( dv_xx + dv_yy ) + dp_y,
                du_x + dv_y ]


    # function definition

    def func(x):

        return np.zeros((len(x),1))

    def func_2(x):

        return np.ones((len(x), 1 ))



    # boundary definition of a unit square domain

    def boundary_l( x, on_boundary ):

        return on_boundary and np.isclose(x[0], 0 )

    def boundary_r( x, on_boundary ):

        return on_boundary and np.isclose(x[0], 1 )

    def boundary_upr( x, on_boundary ):

        return on_boundary and np.isclose(x[1], 1 )

    def boundary_lwr( x, on_boundary ):

        return on_boundary and np.isclose(x[1], 0 )


    geom = dde.geometry.Rectangle([0,0], [ 1, 1 ])


    # defining BC for u, v, and p (component = 0, 1, 2 resp assign)

    bc_lft_u = dde.DirichletBC(geom, func, boundary_l, component = 0 )
    bc_lft_v = dde.DirichletBC(geom, func, boundary_l, component = 1 )

    bc_r_u = dde.DirichletBC(geom, func, boundary_r, component = 0 )
    bc_r_v = dde.DirichletBC(geom, func, boundary_r, component = 1 )

    bc_lwr_u = dde.DirichletBC(geom, func, boundary_lwr, component = 0 )
    bc_lwr_v = dde.DirichletBC(geom, func, boundary_lwr, component = 1 )

    bc_upr_u = dde.DirichletBC(geom, func_2, boundary_upr, component = 0 )
    bc_upr_v = dde.DirichletBC(geom, func, boundary_upr, component = 1 )


    bc_lwr_p = dde.DirichletBC(geom, lambda x: 0.00001 * np.ones((len(x), 1)), boundary_upr, component = 2)



    data = dde.data.PDE(
                     geom,
                     pde,
                     [bc_lft_u, bc_lft_v,
                      bc_r_u, bc_r_v, 
                      bc_lwr_u, bc_lwr_v,
                      bc_upr_u, bc_upr_v,
                      bc_lwr_p ],
                     num_domain = 1000,
                     num_boundary = 500,
                     num_test = 3000
                   )



    layer_size = [2] + [50] * 3 + [3]
    activation = "tanh"
    initializer = "Glorot uniform"

    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile( "adam", lr = 0.001 )

    losshistory, train_state = model.train(epochs = 100)


    
    X = geom.random_points(1000)
    err = 1
    while err > 0.005:
        f = model.predict(X, operator=pde)
        err_eq = np.absolute(f)
        err = np.mean(err_eq)
        print("Mean residual: %.3e" % (err))

        x_id = np.argmax(err_eq)
        print("Adding new point:", X[x_id], "\n")
        data.add_anchors(X[x_id])
        early_stopping = dde.callbacks.EarlyStopping(min_delta=1e-4, patience=2000)
        model.compile("adam", lr=1e-3)
        model.train(
            epochs=10000, disregard_previous_best=True, callbacks=[early_stopping]
        )
        model.compile("L-BFGS-B")
        losshistory, train_state = model.train() 
            
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    
    
    #structured linear points
    
    '''x_lin = np.linspace( 0 , 1 , 400 )
    y_lin = np.linspace( 0, 1 , 400 )
    X = np.vstack( ( x_lin, y_lin ) ).T
    y_pred = model.predict( X )
    #y_output_pde = model.predict(X, operator = pde)
    #print( " the dimension of y_pred is:", y_pred.shape )
    #print( " the shape of y_pred by pde is", y_output_pde.shape)
    
    np.savetxt("Linear_prediction.dat", np.hstack((X, y_pred)))
    '''
    x_geom = geom.uniform_points( 5000, boundary = True )
    y_geom_output = model.predict(x_geom)
    
    #print( "the shape of x_geom :", x_geom.shape)
    #print( "the shape of x_geom :", y_geom_output.shape)
    
    np.savetxt( " y_predicted.dat", np.hstack(( x_geom, y_geom_output)) )
    
    
    
    
if __name__ == "__main__":
    main()

```

Also, I have couple of  doubts:
- Why, new points has been deployed over training points.
```
 print("Adding new point:", X[x_id], "\n")
        data.add_anchors(X[x_id])
```

- How, can we use the saved trained model for further computation without compiling and investing times again and again.

Kindly, Suggest Thank

**Comment by lululxvi** [comment]
- `X = geom.random_points(1000)` has only 1000 points, but `x_id` > 1000. Note: the shape of `f` is `N x 3`.
- Check #57 for model saving/restoring.

**Comment by SanjuSoni** [comment]
#57 give me some ideas for saving and restoring. I'll come to this part later. 
First, I am trying to fix the issue for the callback.

- increasing the random point over geometry the same type of issue occurs.

How can we fix it?

Kindly, suggest.

**Comment by lululxvi** [comment]
I am not sure if I get your point. Could you provide a sample example?

**Comment by SanjuSoni** [comment]
**Early Stopping Callback Issue**


- Based on the  code supplied for early stopping for the training process, I have included few lines for the code which is given as:

- Unfortunately, I encountered the same type of error. This time I have increased the points from the domain.

error is:  
```
Traceback (most recent call last):

  File "D:\PhD_Box\Code\Project_1\Stoke_DeepXDE\stoke.py", line 184, in <module>
    main()

  File "D:\PhD_Box\Code\Project_1\Stoke_DeepXDE\stoke.py", line 142, in main
    print("Adding new point:", X[x_id], "\n")

IndexError: index 257300 is out of bounds for axis 0 with size 100000
```



Code is:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np


import sys
sys.path.insert( 0, "D:/PhD_Box/Code/Project_1/Stoke_2_DeepXDE/deepxde-master/deepxde-master")

import deepxde as dde

import tensorflow as tf


def main():

    def pde( x, y ):

        u, v, p = y[:, 0:1], y[:, 1:2 ], y[:, 2:3]

        du_x = tf.gradients( u , x )[0]
        dv_x = tf.gradients( v , x )[0]
        dp_x = tf.gradients( p , x )[0]

        dp_x, dp_y = dp_x[:, 0:1 ], dp_x[:, 1:2 ]

        du_x, du_y = du_x[:, 0:1], du_x[:, 1:2 ]

        dv_x, dv_y = dv_x[:, 0:1], dv_x[ :, 1:2 ]

        du_xx = tf.gradients( du_x, x )[0][:, 0:1 ]
        du_yy = tf.gradients( du_y, x )[0][:, 1:2 ]

        dv_xx = tf.gradients( dv_x, x)[0][:, 0:1 ]
        dv_yy = tf.gradients( dv_y, x)[0][:, 1:2 ]


        return [-( du_xx + du_yy ) + dp_x,
                -( dv_xx + dv_yy ) + dp_y,
                du_x + dv_y - 1e-10*y[:,2:3] ]


    # function definition

    def func(x):

        return np.zeros((len(x),1))

    def func_2(x):

        return np.ones((len(x), 1 ))



    # boundary definition of a unit square domain

    def boundary_l( x, on_boundary ):

        return on_boundary and np.isclose(x[0], 0 )

    def boundary_r( x, on_boundary ):

        return on_boundary and np.isclose(x[0], 1 )

    def boundary_upr( x, on_boundary ):

        return on_boundary and np.isclose(x[1], 1 )

    def boundary_lwr( x, on_boundary ):

        return on_boundary and np.isclose(x[1], 0 )


    geom = dde.geometry.Rectangle([0,0], [ 1, 1 ])


    # defining BC for u, v, and p (component = 0, 1, 2 resp assign)

    bc_lft_u = dde.DirichletBC(geom, func, boundary_l, component = 0 )
    bc_lft_v = dde.DirichletBC(geom, func, boundary_l, component = 1 )

    bc_r_u = dde.DirichletBC(geom, func, boundary_r, component = 0 )
    bc_r_v = dde.DirichletBC(geom, func, boundary_r, component = 1 )

    bc_lwr_u = dde.DirichletBC(geom, func, boundary_lwr, component = 0 )
    bc_lwr_v = dde.DirichletBC(geom, func, boundary_lwr, component = 1 )

    bc_upr_u = dde.DirichletBC(geom, func_2, boundary_upr, component = 0 )
    bc_upr_v = dde.DirichletBC(geom, func, boundary_upr, component = 1 )


    #bc_lwr_p = dde.DirichletBC(geom, lambda x: 0.00001 * np.ones((len(x), 1)), boundary_upr, component = 2)



    data = dde.data.PDE(
                     geom,
                     pde,
                     [bc_lft_u, bc_lft_v,
                      bc_r_u, bc_r_v, 
                      bc_lwr_u, bc_lwr_v,
                      bc_upr_u, bc_upr_v
                      ],
                     num_domain = 1000,
                     num_boundary = 500,
                     num_test = 3000
                   )



    layer_size = [2] + [50] * 3 + [3]
    activation = "tanh"
    initializer = "Glorot uniform"

    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile( "adam", lr = 0.001 )

    losshistory, train_state = model.train(epochs = 3000)



    X = geom.random_points(100000)
    err = 1
    while err > 0.005:
        f = model.predict(X, operator=pde)
        err_eq = np.absolute(f)
        err = np.mean(err_eq)
        print("Mean residual: %.3e" % (err))

        x_id = np.argmax(err_eq)
        print("Adding new point:", X[x_id], "\n")
        data.add_anchors(X[x_id])
        early_stopping = dde.callbacks.EarlyStopping(min_delta=1e-4, patience=2000)
        model.compile("adam", lr=1e-3)
        model.train(
            epochs=10000, disregard_previous_best=True, callbacks=[early_stopping]
        )
        
        model.compile("L-BFGS-B")
        losshistory, train_state = model.train() 
    
    
        
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    
    

    
    
if __name__ == "__main__":
    main()

```



Kindly, suggest me to get ride of this error:

**Comment by lululxvi** [comment]
As I mentioned before, `X = geom.random_points(100000)` has only 100000 points, but `f = model.predict(X, operator=pde)` is a list of three arrays of size 100000, and thus `err_eq = np.absolute(f)` has size of 300000. Then `x_id` > 100000. `X[x_id]` leads to out of bounds.

**Comment by SanjuSoni** [comment]
**Training and Saving part of the model for 5000 epochs**

- I have added the training the model and saving the data for the first 5000 epochs.
That is working fine and saving the ckpt files up to **model.ckpt- 5000**

- the file stored as :
![trained data](https://user-images.githubusercontent.com/61820415/84230404-7d17f980-ab09-11ea-88d4-ec237466d019.JPG)

- Inserted code as:

  ```
  model = dde.Model(data, net)
    model.compile("adam", lr=0.001)
    checkpointer = dde.callbacks.ModelCheckpoint("./model/model.ckpt", verbose=1, save_better_only=True)
    model.train(epochs = 5000, callbacks=[checkpointer])
```


** Restoring file Failed for model.ckpt-4000 **

- Now, I am trying to restore the saved model at 5000 epochs but I am getting error.

Error is:

INFO:tensorflow:Restoring parameters from ./model/model.ckpt-5000
Traceback (most recent call last):

  File "C:\Users\SUMANT\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)

  File "C:\Users\SUMANT\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)

  File "C:\Users\SUMANT\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)

NotFoundError: Key beta1_power_3 not found in checkpoint
	 [[{{node save_4/RestoreV2}}]]

During handling of the above exception, another exception occurred:







```


Inserted Code is:

```
 model = dde.Model(data, net)
    model.compile("adam", lr=0.001)
    model.restore("./model/model.ckpt-5000")
    #checkpointer = dde.callbacks.ModelCheckpoint("./model/model.ckpt-5000", verbose=1, save_better_only=True)
    model.train(epochs = 7000)
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```


kindly, suggest @jhssyb @lululxvi

**Comment by SanjuSoni** [comment]
- Saving a model is not an issue but restoring a model gives an error.

Kindly suggest me to rectify it.
or, complete code that is successfully executed may help me to learn this technique.

Thanks

**Comment by SanjuSoni** [comment]
> As I mentioned before, `X = geom.random_points(100000)` has only 100000 points, but `f = model.predict(X, operator=pde)` is a list of three arrays of size 100000, and thus `err_eq = np.absolute(f)` has size of 300000. Then `x_id` > 100000. `X[x_id]` leads to out of bounds.

Thanks @lululxvi 
sorry for asking the novice question. Without using the anchor 

` data.add_anchors(X[x_id]) `

- can we train the model up to the desired accuracy without adding this anchor?

Or, can you suggest me a sample code for going to reduce the error with adding anchor in case of my problem? 

- The result will be effected after excluding the anchor over code?

**Comment by SanjuSoni** [comment]
Thanks @lululxvi 
I'll compile my code over linux and will inform you after
